FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential libpq-dev gcc \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/requirements.txt
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY src /app/src

WORKDIR /app/src

ENV DJANGO_SETTINGS_MODULE=src_package.settings
ENV PYTHONPATH=/app/src

CMD ["bash", "-lc", "celery -A src_package worker --loglevel=info"]
