# Generated by Django 5.2.7 on 2025-11-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0002_alter_book_publication_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-id']},
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['isbn'], name='idx_book_isbn'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['publication_year'], name='idx_book_pubyear'),
        ),
    ]
