# Generated by Django 5.2.7 on 2025-11-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0003_alter_book_options_book_idx_book_isbn_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='importtask',
            index=models.Index(fields=['task_id'], name='idx_task_id'),
        ),
    ]
